version: '3'
services:
  srv:
    build:
      context: .
      args:
        ORG: chiswicked
        SERVICE: go-grpc-crud-server-boilerplate
    ports:
      - "8080:8080"
    depends_on:
       - db
  db:
    image: postgres:11.1-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: testusername
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdatabase