version: '3'
services:
  srv:
    build:
      context: .
      args:
        ORG: chiswicked
        SERVICE: go-grpc-crud-server-boilerplate
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
       - db
  db:
    image: postgres:11.1-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: testusername
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdatabase
  prometheus:
    image: prom/prometheus:v2.6.0
    ports:
     - 9090:9090
    depends_on:
     - exporter
  exporter:
    image: prom/node-exporter:v0.17.0
    ports:
     - "9100:9100"
  grafana:
    image: grafana/grafana:5.4.2
    ports:
     - "3000:3000"
    depends_on:
      - prometheus